# Generated by Django 4.2.4 on 2023-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return processing', 'Return processing'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed')], default='Order Confirmed', max_length=50),
        ),
    ]
