# Generated by Django 4.2.4 on 2023-12-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery')], default='Order Confirmed', max_length=50),
        ),
    ]
