# Generated by Django 4.2.4 on 2023-12-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed')], default='Order Confirmed', max_length=50),
        ),
    ]
