# Generated by Django 4.2.4 on 2023-12-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=50),
        ),
    ]
