# Generated by Django 4.2.4 on 2023-12-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Delivered', 'Delivered'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped')], default='Order Confirmed', max_length=50),
        ),
    ]
