# Generated by Django 4.2.4 on 2023-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Returned', 'Returned')], default='Order Confirmed', max_length=50),
        ),
    ]
