# Generated by Django 4.2.4 on 2023-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery')], default='Order Confirmed', max_length=50),
        ),
    ]
