# Generated by Django 4.2.4 on 2023-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return requested', 'Return requested'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped')], default='Order Confirmed', max_length=50),
        ),
    ]
