# Generated by Django 4.2.4 on 2023-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=50),
        ),
    ]
