# Generated by Django 4.2.4 on 2023-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing')], default='Order Confirmed', max_length=50),
        ),
    ]
