# Generated by Django 4.2.4 on 2023-12-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned')], default='Order Confirmed', max_length=50),
        ),
    ]
