# Generated by Django 4.2.4 on 2023-12-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0080_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped')], default='Order Confirmed', max_length=50),
        ),
    ]
