# Generated by Django 4.2.4 on 2024-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0088_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery')], default='Order Confirmed', max_length=50),
        ),
    ]
