# Generated by Django 4.2.4 on 2024-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped')], default='Order Confirmed', max_length=50),
        ),
    ]
