# Generated by Django 4.2.4 on 2024-10-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0092_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery')], default='Order Confirmed', max_length=50),
        ),
    ]
